server:
  port: 8081

spring:
  application:
    name: rococo-gateway
  profiles:
    active: local
  security:
    enabled: false

  grpc:
    client:
      artist-service:
        address: 'localhost:8091'
        negotiation-type: plaintext

  datasource:
    url: jdbc:mysql://localhost:3306/rococo-gateway?createDatabaseIfNotExist=true
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: rococo-gateway
    locations: classpath:db/migration/rococo-gateway

logging:
  level:
    root: INFO

rococo-front:
  base-uri: 'http://localhost:3000'