server:
  port: 8081

spring:
  application:
    name: rococo-gateway
  profiles:
    active: local
  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: http://localhost:9000
           jwk-set-uri: http://localhost:9000/oauth2/jwks
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
      cache:
        period: 3600
    mvc:
      static-path-pattern: /**

grpc:
  client:
    artist-service:
      address: 'static://127.0.0.1:8091'
      negotiation-type: plaintext
    museum-service:
      address: 'static://127.0.0.1:8092'
      negotiation-type: plaintext
    painting-service:
      address: 'static://127.0.0.1:8093'
      negotiation-type: plaintext
    geo-service:
      address: 'static://127.0.0.1:8095'
      negotiation-type: plaintext
    userdata-service:
      address: 'static://127.0.0.1:8096'
      negotiation-type: plaintext

logging:
  level:
    guru.qa.rococo: DEBUG
    io.grpc: DEBUG
    net.devh.boot.grpc: DEBUG
    org.springframework.security: DEBUG

rococo-front:
  base-uri: 'http://localhost:3000'