server:
  port: 8081

spring:
  application:
    name: rococo-gateway
  profiles:
    active: local
  security:
    enabled: false

  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
      cache:
        period: 3600
    mvc:
      static-path-pattern: /**

  datasource:
    url: jdbc:mysql://localhost:3306/rococo-gateway?createDatabaseIfNotExist=true
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: rococo-gateway
    locations: classpath:db/migration/rococo-gateway

grpc:
  client:
    artist-service:
      address: 'static://127.0.0.1:8091'
      negotiation-type: plaintext
    museum-service:
      address: 'static://127.0.0.1:8092'
      negotiation-type: plaintext
    painting-service:
      address: 'static://127.0.0.1:8093'
      negotiation-type: plaintext
    geo-service:
      address: 'static://127.0.0.1:8095'
      negotiation-type: plaintext

logging:
  level:
    guru.qa.rococo: DEBUG
    io.grpc: DEBUG
    net.devh.boot.grpc: DEBUG

rococo-front:
  base-uri: 'http://localhost:3000'