spring:
  security:
    enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

server:
  port: 8081

grpc:
  client:
    artist-service:
      address: 'static://artist.rococo.dc:8091'
      negotiation-type: plaintext
    museum-service:
      address: 'static://museum.rococo.dc:8092'
      negotiation-type: plaintext
    painting-service:
      address: 'static://painting.rococo.dc:8093'
      negotiation-type: plaintext
    geo-service:
      address: 'static://geo.rococo.dc:8095'
      negotiation-type: plaintext
    userdata-service:
      address: 'static://userdata.rococo.dc:8096'
      negotiation-type: plaintext