version: '3.8'
services:
  gateway:
    image: siraxle/rococo-gateway-docker:latest
    container_name: gateway.rococo.dc
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - GRPC_CLIENT_ARTIST_SERVICE_ADDRESS=static://artist.rococo.dc:8091
      - GRPC_CLIENT_ARTIST_SERVICE_NEGOTIATION_TYPE=plaintext
      - GRPC_CLIENT_MUSEUM_SERVICE_ADDRESS=static://museum.rococo.dc:8092
      - GRPC_CLIENT_MUSEUM_SERVICE_NEGOTIATION_TYPE=plaintext
      - GRPC_CLIENT_PAINTING_SERVICE_ADDRESS=static://painting.rococo.dc:8093
      - GRPC_CLIENT_PAINTING_SERVICE_NEGOTIATION_TYPE=plaintext
      - GRPC_CLIENT_GEO_SERVICE_ADDRESS=static://geo.rococo.dc:8095
      - GRPC_CLIENT_GEO_SERVICE_NEGOTIATION_TYPE=plaintext
      - GRPC_CLIENT_USERDATA_SERVICE_ADDRESS=static://userdata.rococo.dc:8096
      - GRPC_CLIENT_USERDATA_SERVICE_NEGOTIATION_TYPE=plaintext
    networks:
      - rococo-master_rococo-network

networks:
  rococo-master_rococo-network:
    external: true