services:
  artist:
    extra_hosts:
      - "rococo-all-db:invalid IP"
  museum:
    extra_hosts:
      - "rococo-all-db:invalid IP"
  painting:
    extra_hosts:
      - "rococo-all-db:invalid IP"
  geo:
    extra_hosts:
      - "rococo-all-db:invalid IP"
  userdata:
    extra_hosts:
      - "rococo-all-db:invalid IP"
  auth:
    extra_hosts:
      - "rococo-all-db:invalid IP"
  gateway:
    extra_hosts:
      - "artist:"
      - "museum:"
      - "painting:"
      - "geo:"
      - "userdata:"
      - "auth:"
