services:
  rococo-all-db:
    container_name: rococo-all-db
    image: mysql:8.3
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-psecret"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - rococo-network

  auth:
    container_name: auth.rococo.dc
    image: siraxle/rococo-auth-docker:latest
    ports:
      - "9000:9000"
    environment:
      - PROFILE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://rococo-all-db:3306/rococo-auth?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secret
    restart: always
    depends_on:
      rococo-all-db:
        condition: service_healthy
    networks:
      - rococo-network

  userdata:
    container_name: userdata.rococo.dc
    image: siraxle/rococo-userdata-docker:latest
    ports:
      - "8098:8098"
      - "8096:8096"
    environment:
      - PROFILE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://rococo-all-db:3306/rococo-userdata?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secret
    restart: always
    depends_on:
      rococo-all-db:
        condition: service_healthy
    networks:
      - rococo-network

  artist:
    container_name: artist.rococo.dc
    image: siraxle/rococo-artist-docker:latest
    ports:
      - "8090:8090"
      - "8091:8091"
    environment:
      - PROFILE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://rococo-all-db:3306/rococo-artist?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secret
    restart: always
    depends_on:
      rococo-all-db:
        condition: service_healthy
    networks:
      - rococo-network

  museum:
    container_name: museum.rococo.dc
    image: siraxle/rococo-museum-docker:latest
    ports:
      - "8094:8094"
      - "8092:8092"
    environment:
      - PROFILE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://rococo-all-db:3306/rococo-museum?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secret
    restart: always
    depends_on:
      rococo-all-db:
        condition: service_healthy
    networks:
      - rococo-network

  painting:
    container_name: painting.rococo.dc
    image: siraxle/rococo-painting-docker:latest
    ports:
      - "8093:8093"
    environment:
      - PROFILE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://rococo-all-db:3306/rococo-painting?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secret
    restart: always
    depends_on:
      rococo-all-db:
        condition: service_healthy
    networks:
      - rococo-network

  geo:
    container_name: geo.rococo.dc
    image: siraxle/rococo-geo-docker:latest
    ports:
      - "8097:8097"
      - "8095:8095"
    environment:
      - PROFILE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://rococo-all-db:3306/rococo-geo?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secret
    restart: always
    depends_on:
      rococo-all-db:
        condition: service_healthy
    networks:
      - rococo-network

  gateway:
    container_name: gateway.rococo.dc
    image: siraxle/rococo-gateway-docker:latest
    ports:
      - "8081:8081"
    environment:
      - PROFILE=docker
      - SPRING_PROFILES_ACTIVE=docker
      - GRPC_CLIENT_ARTIST_SERVICE_ADDRESS=static://artist.rococo.dc:8091
      - GRPC_CLIENT_MUSEUM_SERVICE_ADDRESS=static://museum.rococo.dc:8092
      - GRPC_CLIENT_PAINTING_SERVICE_ADDRESS=static://painting.rococo.dc:8093
      - GRPC_CLIENT_GEO_SERVICE_ADDRESS=static://geo.rococo.dc:8095
      - GRPC_CLIENT_USERDATA_SERVICE_ADDRESS=static://userdata.rococo.dc:8096
    restart: always
    depends_on:
      - auth
      - userdata
      - artist
      - museum
      - painting
      - geo
    networks:
      - rococo-network

  frontend:
    container_name: frontend.rococo.dc
    image: siraxle/rococo-frontend-docker:latest
    ports:
      - "3000:80"
    environment:
      - API_BASE_URL=http://gateway.rococo.dc:8081
    restart: always
    networks:
      - rococo-network

networks:
  rococo-network:
    driver: bridge

volumes:
  mysql_data:
    name: mysql_data