server:
  port: 8097

spring:
  datasource:
    url: jdbc:mysql://rococo-all-db:3306/rococo-geo?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: secret
  grpc:
    server:
      port: 8095
      servlet:
        enabled: false