plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.8'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'com.google.cloud.tools.jib' version '3.4.1'
}

group = 'guru.qa'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:3.5.8"
    }
}

dependencies {
    implementation project(':rococo-grpc-common')

    // gRPC
    implementation platform('io.grpc:grpc-bom:1.68.1')
    implementation 'net.devh:grpc-client-spring-boot-starter:3.1.0.RELEASE'
    implementation 'io.grpc:grpc-netty-shaded'
    implementation 'io.grpc:grpc-services'
    implementation 'jakarta.annotation:jakarta.annotation-api:2.1.1'

    // Spring Boot Starters
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-authorization-server'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // Database
    implementation "org.flywaydb:flyway-core:${project.ext.flywayVersion}"
    implementation "org.flywaydb:flyway-mysql:${project.ext.flywayVersion}"
    runtimeOnly "mysql:mysql-connector-java:${project.ext.mysqlDriverVersion}"

    // Lombok
    annotationProcessor "org.projectlombok:lombok:${project.ext.lombokVersion}"
    compileOnly "org.projectlombok:lombok:${project.ext.lombokVersion}"

    // Test
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

jib {
    container {
        ports = ['9000']
        jvmFlags = ["-Dspring.profiles.active=${System.env.PROFILE ?: 'docker'}", "-Djava.net.preferIPv4Stack=true"]
        environment = [
                'TZ': 'Europe/Moscow',
                'SPRING_DATASOURCE_URL': 'jdbc:mysql://rococo-all-db:3306/rococo-auth?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true',
                'SPRING_DATASOURCE_USERNAME': 'root',
                'SPRING_DATASOURCE_PASSWORD': 'secret'
        ]
        creationTime = 'USE_CURRENT_TIMESTAMP'
        labels = ['maintainer': 'siraxle', 'version': "${project.version}"]
    }
    from {
        image = project.findProperty('dockerImage') ?: 'eclipse-temurin:21-jdk'
    }
    to {
        image = "${project.findProperty('dockerHubName') ?: 'siraxle'}/${project.name}-docker"
        tags = ['latest', "${project.version}"]
    }
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.jibDockerBuild.dependsOn test

tasks.register('printVersion') {
    doLast {
        println project.version
    }
}