server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://rococo-all-db:3306/rococo-artist?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: secret
  grpc:
    server:
      port: 8091
      servlet:
        enabled: false