CREATE TABLE IF NOT EXISTS artist (
    id          BINARY(16) PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    biography   TEXT,
    photo       LONGTEXT,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;